### ISSUE TITLE
Missing Pyanodons recipes

### ISSUE THREAD

**Issue by dengamu** [factoriolab/factoriolab#1010]
**Describe the bug**
Several simple extraction recipes are missing such as:
Salt - Salt mine - requires liquid fuel canisters
Native flora - Collector - requires electricity
Rare-earth ore - Rare-earth extractor - requires Naphtha
Antimony ore - Antimony Drill - requires liquid fuel canisters

Simple steam recipes are also missing such as steam from Electric boiler/Oil burner/(basic)Boiler.

Edit: removed Steam feature request and moved to #1013 and added Antimony ore

**Comment by dcbroad3** [comment]
Steam temperature is not currently accounted for, that is correct. I would consider that more of a feature request since the calculator has never supported it; essentially, the data generator will have to build separate item entries for each encountered steam temperature, as there's no way to specify a temperature of an item in the calculator.

**Comment by dengamu** [comment]
I figured as much. I can edit that part out and make it a new ticket if you'd like.

**Comment by dcbroad3** [comment]
That'd probably be best, I can try to address the actual missing recipes sooner hopefully.

**Comment by dengamu** [comment]
This is still an issue. With the 2.2.1 release many items have no recipe attached to them so the calculator is seeing them as free.

**Comment by dengamu** [comment]
Updates have been fantastic. This ticket is mostly closed except for the Steam production part. The calculator still does not handle basic Steam production from Electric boiler/Oil burner/(basic)Boiler.

**Comment by dcbroad3** [comment]
OK, I checked, and the reason the steam recipes for those boilers are not included is because they do not output 165° steam. Since the calculator cannot handle multiple temperatures currently, it ignores any steam other than 165° steam. This should be covered under the existing request for multiple fluid temperatures.
