### ISSUE TITLE
Request SE/K2/BZ+

### ISSUE THREAD

**Issue by Flagran** [factoriolab/factoriolab#1185]
Hey, 

I would be happy if you added this modpack to your cool and very helpful Factoriolab

Greetings 

**Have you checked whether this mod or set of mods has already been requested?**
Checked :)

**What mod set are you requesting?**
SE/K2/BZ+

**Is this mod set compatible with the latest version of Factorio?"**
Yes, Stable at Experimental: 1.1.91.

**What mods are included in this mod set?**
https://mods.factorio.com/mod/space-exploration
https://mods.factorio.com/mod/Krastorio2
https://mods.factorio.com/mod/bzvery
https://mods.factorio.com/mod/bzchlorine
https://mods.factorio.com/mod/bzgold
https://mods.factorio.com/mod/BrassTacks
https://mods.factorio.com/mod/IfNickel

**Comment by dcbroad3** [comment]
This seems like a fairly arbitrary set of mods. Correct me if I'm wrong, but it doesn't seem like the kind of mod set that would be used by a large number of players. It's always possible to build a mod set yourself, but for now, I don't intend to add this specific mod set to FactorioLab. 
The main issue is `BrassTacks` and `lfNickel` which I can see are from another author, effectively meaning you are asking for a mod set that combines mods from four authors. Unless it's a set that's used by a huge number of players, I'd rather cap it at three overhaul mod sets (e.g. SE+KR2+VBZ might be ok). Otherwise there are just too many possible combinations.
