### ISSUE TITLE
Custom mods and tweaks

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#1304]
i would add that you would be able to load a save in and it would load the recipes from the mods, like you would be able to import mods from a save because i had done some modifications to some mods and have some tweak mods.

I have no idea if this is feasible for you but it would be a really good imporvement in my oppinion

**Comment by dcbroad3** [comment]
It would be amazing if this were feasible, but save files definitely don't include icons, and I highly doubt they contain whole recipes or item/entity data either. 
To be fair I haven't actually tried, so I could look into this a bit to confirm things, but I'm 98% sure the save file wouldn't contain nearly the level of detail required.

**Comment by Valoneu** [comment]
wwll what about getting the savefile for the modlist and u would upload your modfolder before

**Comment by dcbroad3** [comment]
The way the data generator currently works, you have to dump data from the game using the game's actual data-dump functions (there are three different commands that are run, one for the raw data, one for icons, and one for localization - actual names of things in your language)
In theory, it could be possible to upload your whole mods folder and determine the data inside the application, but that would require probably more effort than the entire calculator itself as it stands today. For step 1, you would need to write a Lua language interpreter in JavaScript, so that you could run the lua files as they are run when the game starts up. This alone would be a huge feat. 

This is simply not the kind of thing I would ever plan to attempt. If the calculator had a backend server that could run Lua natively to parse the files, maybe this would be more reasonable, and I think there are some other web services that take a list of Factorio mods and can show you what's inside those mods in a web interface, but that would be a simply massive effort to integrate into FactorioLab. 

If you want full integration like this, I would recommend checking out [YAFC](https://github.com/ShadowTheAge/yafc). Its UI is different and it has to run locally on your computer instead of running in the browser, but because it runs locally on your computer it can directly integrate with your mods folder.
