### ISSUE TITLE
DSP Deuterium Fractionation not recognized with Gas Giant recipe

### ISSUE THREAD

**Issue by Factorionaut** [factoriolab/factoriolab#1338]
**Describe the bug**
Having both Deuterium Fractionation and Gas Giant (the one that produces both Hydrogen/Deuterium) recipes enabled for Deuterium production leads to only Gas Giant recipe actually being accounted for, which leads to huge overshoot on the number of Orbital Collectors required and massive excess of Hydrogen.

**To Reproduce**

1. Add Deuteron Fuel Rod as output item.
2. Select "Recipes" on Deuterium dropdown menu.
3. Configure recipes so that only "Deuterium" (from Particle Collider) and "Gas Giant (Deuterium)" are disabled.
4. See heaps of hydrogen that could've been fractionated and used.

**Screenshots**
![Fractionation bug](https://github.com/factoriolab/factoriolab/assets/144618814/048cbd28-e561-4bee-bfc9-90e0beedad32)
![Excess hydrogen](https://github.com/factoriolab/factoriolab/assets/144618814/d5ddc4ee-3a20-48b8-ac5c-f13e7482e398)

**Comment by dcbroad3** [comment]
I'm not able to reproduce your issue using the steps provided. Could you provide a URL?

When I follow your steps, I end up with this:
https://factoriolab.github.io/list?p=deuteron-fuel-rod*1&r=deuterium-fractionation*1&s=dsp&v=9

**Comment by Factorionaut** [comment]
Sure.

https://factoriolab.github.io/list?z=eJwriNQyMVJL8lArcg7UMox3DgESbiZAwikZxA0CEqVaBvFRWoZqaYZa7vGO8ZHxrvGB8R5aLmrFWmAQqgUF7mpllgBaThRr&v=9

**Comment by Factorionaut** [comment]
> I'm not able to reproduce your issue using the steps provided. Could you provide a URL?
> 
> When I follow your steps, I end up with this: https://factoriolab.github.io/list?p=deuteron-fuel-rod*1&r=deuterium-fractionation*1&s=dsp&v=9

You see, in your link there's Deuterium from Particle Collider and Gas Giant (Deuterium) enabled in Deuterium tab, which is the inverse of the step 3.

**Comment by dcbroad3** [comment]
Ah, I misread 'disabled' as 'enabled'
OK, so the issue here is that the calculator doesn't have any issue with producing a surplus (by default). It doesn't see that as a negative. 
To change, this, set a surplus cost in the advanced settings:
![image](https://github.com/factoriolab/factoriolab/assets/8430702/971a79c7-f447-49fc-8dc1-b4a5ea465a84)

Here is your link with surplus set to 1, which makes the surplus go away:
https://factoriolab.github.io/list?z=eJwriNQyMVJL8lArcg7UMox3DgESbiZAwikZxA0CEqVaBvFRWoZqaYZa7vGO8ZHxrvGB8R5aLmrFWmAQqgUF7lDaUK3MEgABARXC&v=9

**Comment by Factorionaut** [comment]
OK, this makes much more sense now, thanks!
