### ISSUE TITLE
DSP type error loading old save state (reading 'isOne')

### ISSUE THREAD

**Issue by curiousdannii** [factoriolab/factoriolab#1604]
**Describe the bug**
I'm getting an error trying to load an old DSP save state:

```
TypeError: Cannot read properties of undefined (reading 'isOne')
```

My save state:

```
z=eJw90F9PwjAQAPBv04dLJC1kwT3aEkuIOJSBzJcLIjNGEmWiAT6990-W9H69tltv9xU7CNceNxIrCH2PHkqPnzK9lRi3MGSm0MczFBj34HsFDNzL2L2vAO4wNkBPwDg2azOrG0s7szSvzJ45Mpfqk6U.6l55tdUb9Wzp2rxXvVLZ6tS0Sr4tTWarzi09mUf1YGlUrTpqi.p.x0J0XcpAt0-oUGraB4cFhRkNrc.jiUbi-jPGFc.ntJNq3m4o7Ghs5R-4BwEnvDHQ.gY8ynvpgab88YYv2PFHHmnlmU-9yYmDxEJvWSutUGmShaDJUqmVIePaACMnrZrB5cnut.wDWB6HjQ__&v=9
```

All my other save states load correctly, it's just this one that doesn't.

**Comment by dcbroad3** [comment]
Due to a change in the way FactorioLab does stacked belts, this state was broken. Sorry. Here is a fixed state, I just reset all the belts to default.
z=eJwt0MFqAjEQBuC3yeE.SKIs1sMcnJVGBNmWLkp7K9vYCi5boy1bD.PsTcxc8uUfkhmYgTjCPVgzUKc2cNOsxSIzaHxUOWBeLltMEzdUOZxhJxVmJpDD5n56E6n2gM0uAZccC.xZvBYqrb6rh2Kj0Redxp3aqvPssftK71-wkz06-cAZF7niJha8FF6BvfAavBVuwK2kJvyKNJA7cJA0Ma2Bf8Cj8B94ITwxMYy0wR5vCDghNVrf.8xQP0vdmv4Q6cn0IdLK9N8X8uaXnPsHFqFZMQ__&v=11

**Comment by curiousdannii** [comment]
Thank you!

**Comment by dcbroad3** [comment]
Yeah you should be able to set stacking for specific items in the belts column. Let me know if that doesn't satisfy your needs
