### ISSUE TITLE
Add configurable 'cost' for surplus items

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factoriolab#686]
feature request: ability to set a negative value for excess output from secondary processes. (ie, to request a factory with minimum secondary outputs from the processes)

my request is the ability to change the weight of unused items;

simplex mode - the first ticket is a hard coded addition input column on top of the calculations you've done, the second is a multiplier on the cost penalty for unused outputs
that one is more "create X from b of Y and c of Z" - requesting multiple input flows ; that request is sort of a precondition hard coded x positive or negative of an item;
my request is the ability to change the weight of unused items;

simplex mode - the first ticket is a hard coded addition input column on top of the calculations you've done, the second is a multiplier on the cost penalty for unused outputs
we have a penalty cost for resources consumed, but excess output has no benifit or cost.

Requested by Aart Bluestroke in Discord

**Comment by dcbroad3** [comment]
Likely feasible by adding extra rows for surpluses in the canonical matrix and assigning a cost, only doing so if the cost is configured to be > 0 (where 0 is default).

**Comment by dcbroad3** [comment]
+1 from Sebbo in Discord

**Comment by EzzaB** [comment]
This would be useful on a configurable per-item basis.

In Nullius some fluids are trivial to void (oxygen for example) and therefore don't really need a (large) surplus penalty. Others (chlorine) require a lot of processing steps to convert them into a fluid that can be voided, requiring more items and potentially adding even more by-products. We'd really like to avoid producing too much if we can, and if we can't avoid surplus then we want to include the entire production chain to get it to a voidable (cheaper) state as part of the generated factory output so it will not back up.

Here are two examples of where adding surplus costs only to specific items could improve the results and assist in avoiding any backups from by-products.

See the link at the bottom (markdown doesn't like it - too long?)

### First example
In the link Factoriolab has solved with a large surplus of chlorine which, as mentioned above, is difficult to deal with. It has presumably done this because it decided that is the most effective way to get the hydrogen it requires.
An easy fix is to simply run a lot more "Water electrolysis" instead of "Saline electrolysis" and avoid generating the chlorine in the first place. We can easily void the additional oxygen this generates. 
Another potential solution would be to prioritise PVC plastic (which uses chlorine) over polypropylene.
If chlorine had a large cost for any surplus while oxygen had low/none then I'd assume the solver would be able to come to one or a combination of these solutions.

### Second example
In the same link there is also a surplus of "Sodium hydroxide". Disregard for a moment that fixing the chlorine problem above would probably fix this as well (it is a by-product of the same recipe). Unlike the chlorine we can't really use an alternate recipe to avoid generating it. There are only two recipes that use sodium hydroxide - turn it into "Caustic Solution" (which can be voided) or turn it into Caustic Solution slightly more efficiently.
Currently Factoriolab is using the more efficient recipe despite the surplus. We ideally want it to use the less efficient recipe to use up more sodium hydroxide (unless the alternative type of water is super expensive I guess). Making it use the less efficient recipe would help but will not completely fix the problem in most cases. We want to make sure ALL the sodium hydroxide is converted into caustic solution, even if that puts the caustic solution into a huge surplus (it is easy to void).
If sodium hydroxide is given a large surplus cost and caustic solution has low/none then hopefully the solver would figure these out as well.

https://factoriolab.github.io/list?z=eJwVmLdy60y3Bd.mC06VWHSiCQmPgSPhgeTWYAB6IxqRlIJ-9qt.J6tqBas73l9C.hv8G.2fPfxf.NfE.-38w7-.S7r.7v.-fdBjwgLtA22ANkQboU3RZmhztL9eQ3PQPDQfLUAL0SK0FVqKlqEVaBWaRFNoLVqHtkbbol3QvtCuaDe0O9oD7RvtifZCe6N.oPfQ--gD9CH6CH2M.ok-QZ-iz9Dn6At0Dd1At9BtdAfdRRfoHnqAHqJH6Ev0FXqMnqCn6Bl6jl6gl-gVeo0u0Rt0hd6id-gb9C36Dn2PfkA.op.Qz-gX9C.0K.oN.Y7-QP9Gf6K.0P9sf9B.MT4wehh9jAHGEGOEMcb4xJhgTDFmGHMMDUPHMDBMDAvDxnAwXAyB4WH4GAFGhLHEWGHEGAlGipFh5BgFRolRYdQYEqPBUBgtRoexxthgbDF2GHuMA8YR44RxxrhgfGFcMW4Yd4wHxjfGE-OF8cb4wfzA7GH2MQeYQ8wR5hjzE3OCOcWcYc4xF5g6poFpYlqYNqaD6WIKTA.TxwwwQ8wIc4m5wowxE8wUM8PMMQvMErPCrDElZoOpMFvMDnONucHcYu4w95gHzCPmCfOMecH8wrxi3jDvmA.Mb8wn5gvzjfln.ov1gdXD6mMNsIZYI6wx1ifWBGuKNcNaYGlYOpaBZWJZWDaWiyWwPCwfK8AKsSKsJdYKK8ZKsFKsDCvHKrBKrAqrxpJYDZbCarE6rDXWBmuLtcPaYx2wjlgnrDPWBesL64p1w7pjPbC-sZ5YL-wP7B52H3uAPcQeYY-xP7En2FPsGfYce4GtYevYBraJbWHb2A62iy2wPWwfO8AOsSPsJfYKO8ZOsFPsDDvHLrBL7Aq7xpbYDbbCbrE77DX2BnuLvcPeYx-wj9gn7DP2BfsL-4p9w75jP7C.sZ.Yf9pv7B.sX5wPnB5OH2eAM8QZ4YxxPnEmOFOcGc4cZ4Gj4eg4Bo6JY-HYOA6OiyNwPBwfJ8AJcSKcJc4KJ8ZJcFKcDCfHKXBKnAqnxpE4DY7CaXE6nDXOBmeLs8PZ4xxwjjgnnDPOBecL54pzw7njPHC-cZ44L5w3zg.OL-4Hbg-3jzvAHeKOcMe4n7gT3CnuDHeOu8DVcHVcA9fEtXBtXAfXxRW4Hq6PG-CGuBHuEneFG-MmuCluhpvjFrglboVb40rcBlfhtrgd7hp3g7vF3eHucQ-4R9wT7hn3gvuFe8W94d5xH7jfuE.cF-4b9wf3F.GB6CH6iAFiiBghxohPxAQxRcwQc8QCoSF0hIEwERbCRjgIFyEQHsJHBIgQESGWiBUiRiSIFJEhckSBKBEVokZIRINQiBbRIdaIDWKL2CH2iAPiiDghzogL4gtxRdwQd8QD8Y14Il6IN-IH8YvXxxvijfDGeJ94M7wFnoan4xl4Jp6FZ-M5eC6ewPPwfLwAL8SL8JZ4K7wYL8FL8TK8Cq.Gk3gNnsJr8Tq8Nd4Gb4u3w9vjHfCOeCe8M94F7wvvinfDu-M98L7xnngvvB.8Hn4ff4g.wh.jf-JP8Kf4M.wFvoHv4wf4IX6Ev8Rf4cf4CX6Kn-FLfIXf4m.xd.h7.AP-Ef-Ef8a.4H.hX.Fv-Hf8B.43.hP.hf.G.6P.EnwQ9Aj6BAOCEcGY4JNgQjAlmBHMCXQCi0AQeAQ-QUAQEkQES4IVQUyQE5QEFUFHsCbYEGwJdgRHggvBleBGcCf4JngT.BD8Ek4JZ4RzwgWhRqgTmoQ2oUMYES4JY8KEMCOsCGtCSagIW8KOcE24IdwS7gkPhEfCE-EX4Y3wQfgkfBP-Eo2IxkQToinRnEgnMohMIovIJnKIBJFH5BMFRAlRSlQQVUSSqCFqiTqiNdGWaEd0JroQ3YjuRN9EL6IflgOWM5YLljrLkqVi2bHcsdyzPLA8sryyvLG8s3yw.Gb5YqWx0lkZrExWFiuHlWDlsZKsGlYtq47VhtWW1Z7VgdWZ1YXVldWNuEfcJx4QD4lHxGPiCfGMeE68INaIdWKT2Cb2iH3igDgkjoiXxCvimDghTokz4py4IC6JK-KaWBI3xIq4Je6I18Rb4h3xhfiL-Er8R78TP4ifxC.iN.EvyYJEI9FJDBKbxCFxSQSJR-KThCRLkhVJTJKSZCQFyYHkSHIiOZNcSR4kT5I36Qdpj7RPOiGdkc5JTVKL1CcNSEPSiHRJuiKNSRPSlDQjzUlL0oq0Jm1IFWlL2pGuSQ-kR9IT6YX0RnonfZL-gX7JPsh6ZH2yAdmQbEQ2Jvskm5BNyWZkc7IFmUVmk8VkCVlOVpCVZBVZTSbJFFlL1pGtyTZkW7Id2Z7sRHYmu5DdyO5kD7IX2Zvsh-yX.IO8R94nH5APyUfkY.IJ-ZR8Rj4nX5Br5Dq5QW6SW-QeuU8ekIfkEfmSfEUekyfkKXlGnpMX5CV5RV6TS.KGXJG35B35mnxDfiA.kp.Iz-R38gf5N.mL.E3-Q7Gg0Ch0CoPCpLAobAqHwqUQFB6FTxFQhBQRxZJiRZFSZBQ5RUFRUlQUkmJDsaXYUewpDhRHihPFmeJC8UX5Qdmj7FMOKIeUI8ox5SflhHJKOaOcU2aUOWVBqShbyo5yTbmh3FLuKPeUB8oj5YnyTHmh.Ju9Ut4o75QPym.KJ-WL8k35Q.lL1acaUA2pRlRjqk-qCdWUakY1p1pQaVQ6lUFlUllUNpVD5VIJKo.KpwqoQqqIakm1ooqpEqqUKqPKqQqqkqqiqqk6qh3VnupAdaQ6UZ2pLlRfVFeqG9Wd6kH1TfWk-qH6pf6g7lH3qQfUQ-oR9Zj6k3pCPaWeUc-pF9SC2qMuqCtqSd1QK-qWuqNeU2-ot9Q76j31gfpIfaa-UH9RX6lv1HfqB.U39ZP6Rf2m.qH-RX4ge8g-coAcIkfIMfITOUFOkTPkHLlAakgdaSBNpIW0kQ7SRQqkh.SRATJERsglcoWMkQkyRWbIHFkgS2SFrJES2SAVskV2yDVyg9wid8g98oA8Ik.IM.KC.EJekTfkHflAfiOfyBfyjfxB.tJ80PRo-jQDmiHNiGZM80kzoZnSzGjmNAsajUanMWhMGovGpnFoXBpB49H4NAFNSBPRLGlWNDFNQpPSZDQ5TUFT0lQ0NY2kaWgUTUvT0axpNjRbmh3NnuZAc6Q50ZxpLjRfNDeaO82D5pvmSfOiedP80PyiPlA9VB81QA1RI9QY9YmaoKaoGWqOWqA0lI4yUCbKQtkoB-WiBMpD-agAFaIi1BK1QsWoBJWiMlSOKlAlqkLVKIlqUArVojrUGrVBbVE71B51QB1RJ9QZdUF9oa6oG-qOeqC-UU.UC.VG.aB-aT9oe7R92gHtkHZEO6b9pJ3QTmlntHPaBa1Gq9MatCatRWvTOrQuraD1aH3agDakXdKuaGPahDalzWhz2oK2pK1oO9o17YZ2S7uj3dMeaI-0J9oz7YX2i.ZK-6R90b5pf2h.6T7oenQTuindjG5Ot6DT6HQ6g86ks-gcOkHn0fl0K7qErqbr6DZ0O7o93YHuSHeiO9M96V50b9Yaa521wdpkbbG2WcesM9Y564J1ybpi3bBWrFuOvP.32Vj-W.zr.xv995z-P7I.dsI_&v=7https://factoriolab.github.io/list?z=eJwVmLdy60y3Bd.mC06VWHSiCQmPgSPhgeTWYAB6IxqRlIJ-9qt.J6tqBas73l9C.hv8G.2fPfxf.NfE.-38w7-.S7r.7v.-fdBjwgLtA22ANkQboU3RZmhztL9eQ3PQPDQfLUAL0SK0FVqKlqEVaBWaRFNoLVqHtkbbol3QvtCuaDe0O9oD7RvtifZCe6N.oPfQ--gD9CH6CH2M.ok-QZ-iz9Dn6At0Dd1At9BtdAfdRRfoHnqAHqJH6Ev0FXqMnqCn6Bl6jl6gl-gVeo0u0Rt0hd6id-gb9C36Dn2PfkA.op.Qz-gX9C.0K.oN.Y7-QP9Gf6K.0P9sf9B.MT4wehh9jAHGEGOEMcb4xJhgTDFmGHMMDUPHMDBMDAvDxnAwXAyB4WH4GAFGhLHEWGHEGAlGipFh5BgFRolRYdQYEqPBUBgtRoexxthgbDF2GHuMA8YR44RxxrhgfGFcMW4Yd4wHxjfGE-OF8cb4wfzA7GH2MQeYQ8wR5hjzE3OCOcWcYc4xF5g6poFpYlqYNqaD6WIKTA.TxwwwQ8wIc4m5wowxE8wUM8PMMQvMErPCrDElZoOpMFvMDnONucHcYu4w95gHzCPmCfOMecH8wrxi3jDvmA.Mb8wn5gvzjfln.ov1gdXD6mMNsIZYI6wx1ifWBGuKNcNaYGlYOpaBZWJZWDaWiyWwPCwfK8AKsSKsJdYKK8ZKsFKsDCvHKrBKrAqrxpJYDZbCarE6rDXWBmuLtcPaYx2wjlgnrDPWBesL64p1w7pjPbC-sZ5YL-wP7B52H3uAPcQeYY-xP7En2FPsGfYce4GtYevYBraJbWHb2A62iy2wPWwfO8AOsSPsJfYKO8ZOsFPsDDvHLrBL7Aq7xpbYDbbCbrE77DX2BnuLvcPeYx-wj9gn7DP2BfsL-4p9w75jP7C.sZ.Yf9pv7B.sX5wPnB5OH2eAM8QZ4YxxPnEmOFOcGc4cZ4Gj4eg4Bo6JY-HYOA6OiyNwPBwfJ8AJcSKcJc4KJ8ZJcFKcDCfHKXBKnAqnxpE4DY7CaXE6nDXOBmeLs8PZ4xxwjjgnnDPOBecL54pzw7njPHC-cZ44L5w3zg.OL-4Hbg-3jzvAHeKOcMe4n7gT3CnuDHeOu8DVcHVcA9fEtXBtXAfXxRW4Hq6PG-CGuBHuEneFG-MmuCluhpvjFrglboVb40rcBlfhtrgd7hp3g7vF3eHucQ-4R9wT7hn3gvuFe8W94d5xH7jfuE.cF-4b9wf3F.GB6CH6iAFiiBghxohPxAQxRcwQc8QCoSF0hIEwERbCRjgIFyEQHsJHBIgQESGWiBUiRiSIFJEhckSBKBEVokZIRINQiBbRIdaIDWKL2CH2iAPiiDghzogL4gtxRdwQd8QD8Y14Il6IN-IH8YvXxxvijfDGeJ94M7wFnoan4xl4Jp6FZ-M5eC6ewPPwfLwAL8SL8JZ4K7wYL8FL8TK8Cq.Gk3gNnsJr8Tq8Nd4Gb4u3w9vjHfCOeCe8M94F7wvvinfDu-M98L7xnngvvB.8Hn4ff4g.wh.jf-JP8Kf4M.wFvoHv4wf4IX6Ev8Rf4cf4CX6Kn-FLfIXf4m.xd.h7.AP-Ef-Ef8a.4H.hX.Fv-Hf8B.43.hP.hf.G.6P.EnwQ9Aj6BAOCEcGY4JNgQjAlmBHMCXQCi0AQeAQ-QUAQEkQES4IVQUyQE5QEFUFHsCbYEGwJdgRHggvBleBGcCf4JngT.BD8Ek4JZ4RzwgWhRqgTmoQ2oUMYES4JY8KEMCOsCGtCSagIW8KOcE24IdwS7gkPhEfCE-EX4Y3wQfgkfBP-Eo2IxkQToinRnEgnMohMIovIJnKIBJFH5BMFRAlRSlQQVUSSqCFqiTqiNdGWaEd0JroQ3YjuRN9EL6IflgOWM5YLljrLkqVi2bHcsdyzPLA8sryyvLG8s3yw.Gb5YqWx0lkZrExWFiuHlWDlsZKsGlYtq47VhtWW1Z7VgdWZ1YXVldWNuEfcJx4QD4lHxGPiCfGMeE68INaIdWKT2Cb2iH3igDgkjoiXxCvimDghTokz4py4IC6JK-KaWBI3xIq4Je6I18Rb4h3xhfiL-Er8R78TP4ifxC.iN.EvyYJEI9FJDBKbxCFxSQSJR-KThCRLkhVJTJKSZCQFyYHkSHIiOZNcSR4kT5I36Qdpj7RPOiGdkc5JTVKL1CcNSEPSiHRJuiKNSRPSlDQjzUlL0oq0Jm1IFWlL2pGuSQ-kR9IT6YX0RnonfZL-gX7JPsh6ZH2yAdmQbEQ2Jvskm5BNyWZkc7IFmUVmk8VkCVlOVpCVZBVZTSbJFFlL1pGtyTZkW7Id2Z7sRHYmu5DdyO5kD7IX2Zvsh-yX.IO8R94nH5APyUfkY.IJ-ZR8Rj4nX5Br5Dq5QW6SW-QeuU8ekIfkEfmSfEUekyfkKXlGnpMX5CV5RV6TS.KGXJG35B35mnxDfiA.kp.Iz-R38gf5N.mL.E3-Q7Gg0Ch0CoPCpLAobAqHwqUQFB6FTxFQhBQRxZJiRZFSZBQ5RUFRUlQUkmJDsaXYUewpDhRHihPFmeJC8UX5Qdmj7FMOKIeUI8ox5SflhHJKOaOcU2aUOWVBqShbyo5yTbmh3FLuKPeUB8oj5YnyTHmh.Ju9Ut4o75QPym.KJ-WL8k35Q.lL1acaUA2pRlRjqk-qCdWUakY1p1pQaVQ6lUFlUllUNpVD5VIJKo.KpwqoQqqIakm1ooqpEqqUKqPKqQqqkqqiqqk6qh3VnupAdaQ6UZ2pLlRfVFeqG9Wd6kH1TfWk-qH6pf6g7lH3qQfUQ-oR9Zj6k3pCPaWeUc-pF9SC2qMuqCtqSd1QK-qWuqNeU2-ot9Q76j31gfpIfaa-UH9RX6lv1HfqB.U39ZP6Rf2m.qH-RX4ge8g-coAcIkfIMfITOUFOkTPkHLlAakgdaSBNpIW0kQ7SRQqkh.SRATJERsglcoWMkQkyRWbIHFkgS2SFrJES2SAVskV2yDVyg9wid8g98oA8Ik.IM.KC.EJekTfkHflAfiOfyBfyjfxB.tJ80PRo-jQDmiHNiGZM80kzoZnSzGjmNAsajUanMWhMGovGpnFoXBpB49H4NAFNSBPRLGlWNDFNQpPSZDQ5TUFT0lQ0NY2kaWgUTUvT0axpNjRbmh3NnuZAc6Q50ZxpLjRfNDeaO82D5pvmSfOiedP80PyiPlA9VB81QA1RI9QY9YmaoKaoGWqOWqA0lI4yUCbKQtkoB-WiBMpD-agAFaIi1BK1QsWoBJWiMlSOKlAlqkLVKIlqUArVojrUGrVBbVE71B51QB1RJ9QZdUF9oa6oG-qOeqC-UU.UC.VG.aB-aT9oe7R92gHtkHZEO6b9pJ3QTmlntHPaBa1Gq9MatCatRWvTOrQuraD1aH3agDakXdKuaGPahDalzWhz2oK2pK1oO9o17YZ2S7uj3dMeaI-0J9oz7YX2i.ZK-6R90b5pf2h.6T7oenQTuindjG5Ot6DT6HQ6g86ks-gcOkHn0fl0K7qErqbr6DZ0O7o93YHuSHeiO9M96V50b9Yaa521wdpkbbG2WcesM9Y564J1ybpi3bBWrFuOvP.32Vj-W.zr.xv995z-P7I.dsI_&v=7
