### ISSUE TITLE
Crash while loading recipes

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#749]
**Describe the bug**
When i have KS2 + SE selected and i enable all recipes it crashes

**To Reproduce**
Select KS2 + SE
click on enable all recipes
site crashes

**Expected behavior**
it would load all recipes

**Screenshots**
no need

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser OperaGX
 - Version LVL 3 (core: 86.0.4363.64)

**Comment by dcbroad3** [comment]
Can you clarify what you mean when you say the site crashes? I just tested and this is working as expected. It doesn't find a solution within five seconds on my machine, but that's expected in this case. 

If I disable all the "matter", "crushing", and "scrapping" recipes only, I get a solution in about 12 seconds.  

The calculator is not highly performant with large matrices. I have some plans to improve this but part of the issue is the complexity of the problem at hand, linear programming can be highly resource intensive.

**Comment by dcbroad3** [comment]
Testing a little more, you get the best results with:

* Item to matter recipes disabled
* Matter to item recipes disabled
* Crush inserter recipes disabled
* Empty barrel recipes disabled

Looks like this comes out to 103 recipes disabled, I'll update the data set to make this the default.

**Comment by Valoneu** [comment]
Thanks ill try when this is the default :)

**Comment by Valoneu** [comment]
![image](https://user-images.githubusercontent.com/60077591/171679108-af79c0f4-262b-43e3-a87d-bec5a290b330.png)

**Comment by dcbroad3** [comment]
I have not. No solution found is a more serious problem, it means the solver found a loop that it couldn't solve like the one described in the dialog, that is much more difficult for me to resolve. I'll see if I can get reasonable defaults set up in these data sets, looks like I might have been mistaken initially and my suggested default doesn't work as well as I thought, but still working on it.

**Comment by Valoneu** [comment]
![image](https://user-images.githubusercontent.com/60077591/172462211-3fd54afc-7c7d-443a-82ea-002bb977729a.png)
loaded SE +K2 and clicked on space science again
