### ISSUE TITLE
DSP Hydrogen Calculation Incorrect

### ISSUE THREAD

**Issue by CircuitGuy** [factoriolab/factoriolab#767]
**Describe the bug**
This recipe is showing a surplus of hydrogen, but it is incorrect. There is a deficit. It seems to be triggered by choosing not to 'include' hydrogen on the main screen.

https://factoriolab.github.io/list?z=eJxNxrkKwlAUhOG3OcWA4oLaT8TrgiJIMLEJxAVCBMWgJM08u.dY-cN8zPOB2cDKpVU8Y1iw56TOwamcvtNFmrg2LgNW9uIVmBcs3fR3t27nJAtgbTcEa4CpOBLH4k5MxUzMxVq8Kwna66hcJ11U660WsQ3-CvaZfAHtjC9L

Scroll to the Matrix - it shows a surplus of 3.168 per second. The sankey flow diagram also shows the 'correct' behavior and shows an unbalanced negative hydrogen (even being mindful to exclude the 'fake' stream to the fractionators).

The actual production and consumption of hydrogen in this factory is:

| Process | Hydrogen |
| ---- | ---- |
| Plasma Refining | 1.2 |
| X-Ray (Input) | -1.7 |
| X-Ray (Output) | 2.55 |
| Deut (Net H Out) | -2.987 |
| Casimir | -7.8 |
| **NET** | **-8.73 per sec** |

Note that the behavior changes drastically if you 'include' Hydrogen in the list tab. It seems to recognize there is a net hydrogen deficit and rearranges the factory to produce more. 

**What I Expected**
Choosing not to include hydrogen is great - this production line should be a net consumer of hydrogen. I wanted the calculator to tell me how much, but it was showing an (incorrect) surplus instead.

**Comment by dcbroad3** [comment]
The issue is that the calculator assumes it already has all the hydrogen it needs, and thus any extra hydrogen produced by any of the other recipes required is thus treated as surplus. 
I'll see if I can make an exception in this case and treat the amount as not surplus if the item is ignored.

**Comment by dcbroad3** [comment]
Pushing a potential fix to https://factoriolab.github.io/staging/dsp
Let me know if this seems to give you the expected result. I think it still needs some refining for more potential edge cases but it seems to give the expected result in your specific case now.

**Comment by CircuitGuy** [comment]
> Pushing a potential fix to https://factoriolab.github.io/staging/dsp
Let me know if this seems to give you the expected result. I think it still needs some refining for more potential edge cases but it seems to give the expected result in your specific case now.

I'm not seeing the fix.
https://factoriolab.github.io/staging/matrix?z=eJxNxs0KglAYhOG7OYuBIotqP0anH4ogDmkbQSsQgyIpdDPX3vla9cI8zPOB-ciVK1ezQlJwYATjaNTG0OgjbVwGrIsOiXvxCiwKlmb43Z3ZG-kS2LgbvGuBmTgWJ-JeDGIm5mIj3pV6HXRSrrMuavRWh9gWf3n3mX4B7OIvSw__

I'm still seeing a surplus of hydrogen when it's ignored as an input.

**Comment by dcbroad3** [comment]
So to be clear, the fix is for the list tab, not the matrix tab. The matrix tab will still list hydrogen as a surplus, there's really no way to avoid that. The matrix tab is kind of a peek under the hood, and under the hood the simplex solution tells us that to produce the desired products in this case we end up with a surplus of hydrogen (we produce more than what is required to feed the recipes).

I deleted my original comment because I am not 100% sure I understand the problem here yet and I don't want to assume too much; even the statement above may be wrong. I hope to investigate more today or tomorrow and get to the bottom of it. My intent with the fix in the staging environment was only to correct the List tab, though.
