### ISSUE TITLE
DSP gas giant

### ISSUE THREAD

**Issue by lordyoyo** [factoriolab/factoriolab#813]
Dyson Sphere Program calculator uses gas giant extraction as a single recipe tapping two resources at the same time (fire ice or deuterium, and hydrogen), this causes weird behavior in the calculator, since it thinks that even when you're only getting one of the resources, you're getting a proportionate excess of the other one. Could be easily solved by having the 4 gas giant resources (3, but hydrogen has different gains on the two different types, so should be treated separately) as 4 different recipes instead of just 2.

**Comment by dcbroad3** [comment]
I've seen this request before, which makes me think I must be missing something. Can orbital collectors be configured to collect only one resource at a time? My understanding was that they always collect hydrogen and either fireice or deuterium.

**Comment by lordyoyo** [comment]
They collect permanently and store it in their inventory. But you can request either one of those resources for a production line with ILS, and this doesn't affect the collection of either resource (unlike for example with oil refinement, where if one line gets filled, the other also can't function, due to the factory shutting down if either resource is full).
The issue is that the calculator treats the orbital collectors' output the same as the refineries', so if you request only fire ice, hydrogen will nonetheless automatically show up as excess. This can be an issue further down the line, where you create graphene and hydrogen from the fire ice, and you want to dump the exact amount of extra hydrogen created, but the calculator shows weird values, since it thinks it also has hydrogen from the gas giant too.

**Comment by dcbroad3** [comment]
Ok, that lines up with my understanding. One thing you can do is expand the hydrogen step and it will tell you exactly how much hydrogen comes from orbital collectors vs other sources. I still think it's appropriate to treat it as an excess, since it is still another source of hydrogen that can be tapped.

**Comment by dcbroad3** [comment]
So it feels like there are two different classes of surplus. 

* The traditional: items produced as a byproduct that must be disposed or stored explicitly otherwise production will back up
* This case: extra items can be produced by this recipe, but if unused, they do not need to be disposed or stored

I still think of the second case as a surplus, it's not exactly like an untapped vein because it is already tapped; it doesn't require any extra factories to produce the other items. I'll give it some thought, perhaps there's a way to distinguish the two types of surplus, e.g. preserve the recipes as they are but ignore surpluses from the gas giant recipes.

**Comment by lordyoyo** [comment]
This is a specific problem only for gas giant products, since Hydrogen is generated by 6 recipes, 2 of those being the gas giant extraction, and used in 8 recipes, with 7 of them having a chance of overlapping with the other product's production chain too. If they were treated as separate mining facilities, there are very few things that would change. One is that if you add both of them deliberately to the chain, is the amount of Orbital Collectors shown at the overview at the end. But that is useless in the first place, since the mining rates are variable, and when you tap a gas giant, you pretty much always want to just plonk down the 40 extractors and forget about it. The other change would be that the two recipes would have to still be on the same toggle in the recipe disable menu.
I also still think it should be treated as an untapped vein, it's pretty much the same as if you dropped down a miner on a mineral vein, built some storage and left it there, with 0 intention of using it. The only issue is that its mere existence screws up some calculations, because the calculator thinks that you already have that resource available in the chain. The real fancy and nice solution to all of this would be if I could mark specific sources of products to be ignored. This would also solve the similar problem with the Blender in Satisfactory, since most fluid outputs from that can be used for power generation, which can't be added to the calculator (yet?).
On a side note, when I thought up that miner comparison, I also realized that after finalizing the other product's utilization, you can add the extra from the gas giant as a product to be made in the top, and this solves the original issue in most cases. The dumb part is that H2 can be used to create even more H2, and if you want to include that in the calculator, it can still mess up with this, but that is really an edge case.

**Comment by dcbroad3** [comment]
Closed in #843
