### ISSUE TITLE
integer building numbers

### ISSUE THREAD

**Issue by aeosynth** [factoriolab/factoriolab#875]
I'd like an option for all buildings to be rounded up to integers. I can't place fractional buildings, and end up rounding up manually, and with multiple steps rounding up, earlier steps may need more than a simple rounding up adjustment.

**Comment by dcbroad3** [comment]
You can use the column settings (the button in the upper left of the list view) to reduce the number of digits to 0 for the factories column. This will round them all up to whole integers. 

Note: because when you round up, not all of the factories are operating 100% of the time, earlier steps never need more than a simple rounding up adjustment. They are also not running 100% of the time. E.G. if you need 1.5 assemblers to produce the gears you need, and you stamp down two, that means one of them is only operating 50% of the time. Therefore, you don't actually need more iron plates to support it, you still need the exact same amount. 

I will close this issue, but I'll consider reopening it if we discuss further and you still feel there is an issue.
