### ISSUE TITLE
So laggy

### ISSUE THREAD

**Issue by Valoneu** [factoriolab/factoriolab#880]
https://factoriolab.github.io/next/list?z=eJwtydtS4kAUheG34aKrsIIDRC8JSXfSJJGkW6W9oQJycgRRTsrF.-xDGGtXfWvvtbdL0fI8bxy9i-7FU20Q1aZFbT6qlYvaB1trrr2-PvNata6NVW3SrB30a-21T4YXG5O08TXyhai4TmPeEiWVaIlKhONClPU2Nr.ZE9fPuPy9Z.-zsRMiGBA8EowIpgSvBDOCM.0W.YJwRbghckQVsom8QXrIFvIW2UZ2kF2kj7xD3iP3yB.kGdVDBag-KkRFKIlSqBiVoDRqgEpRBXFMXBJb4jXJhOQT.YAu0S.oCj1BT9Gv6Bl6jl6gl-gV-g39F.2OXqM36A8GGwYXtww-SdukHdIu6Yr0RGbJHsmeyEZkjuyFrCKbkE3Ju-Q--Rf5jnxPfiA.kp8YegwXDN8Ynil8CkVRUOwoDpQhZUQpKRXlE2VFucA0MTcYD9PC3GL-YNqYDqaL8TF3mHtMD.OF2WH2mAPmiDlhvjE.mDO2hw2wfWyIjbASq7AxNsFqnj943jKKcB2cj3O4CjfBTXEz3By3xK1wO9wed8AdcSfctwgv01yIMGkcO.8A0yjjGw__ i have this list and its lagging so much its unnusable

**Comment by Valoneu** [comment]
maybe you could have button where you can turn off and on automatic recalculating when changing smthing

**Comment by Valoneu** [comment]
oh okay :) well i hope it gets find out what is it

**Comment by Valoneu** [comment]
now it doesent even want to load for me :/

**Comment by dcbroad3** [comment]
OK, there are a few different issues in play. Leaving this as notes to myself as much as anything, FYI. 

1) For every product, the calculator does a separate solve step in order to populate the "Select limit step" dropdown. This should really not be done up-front, it should be calculated when the user clicks on the dropdown or something like that, since most of the time the dropdown is not used. This means that the calculator takes linearly longer for each product that is added. 
2) There are a few places where minor optimizations could help, such as `RationalRecipe.produces`, which should likely be a simple lookup instead of a function. This is nontrivial because recipes are mutated while building the dataset and accounting for beacons / modules / proliferator / burner fuel inputs. 
3) Long step lists take a long time to render. There should likely be some type of paging or virtualization to avoid rendering extremely long step lists up-front. 

I'll try to address each of these at some point.

**Comment by Valoneu** [comment]
do you have any idea when, like if i should wait or should i commit to use it even when so laggy its pain in the ass

**Comment by dcbroad3** [comment]
It will likely be a while before I can get time to work on these, apologies.

**Comment by Valoneu** [comment]
its fine i was just asking, at the end of the day you are doing it for free and i appreciate that

**Comment by dcbroad3** [comment]
For what it's worth: I found that turning off most of the optional columns helps performance a little bit. 
Most of all, the massive number of beacon dropdowns the calculator is trying to render takes a while, so even just disabling the beacons column when you're not using it would help.

**Comment by dcbroad3** [comment]
#942 should resolve the main cause of lag since it will remove the need to calculate a solution for each individual product beforehand. (This will also remove the limit steps as they will be obsoleted by that feature)
