### ISSUE TITLE
Ability to add overall limits on quantities of specific items

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factoriolab#942]

**Comment by TacticalMook** [comment]
This was brought to my attention today. It seems there are two things FactorioLab cannot do, that SatisfactoryTools can.

1. SFTools lets you set multiple limiting steps (albeit only for raw resources).

2. Because 1 is not supported, FLab has never needed to support the simultaneous use of multiple alt-recipes which produce the same product.

[Here is the desired result in SatisfactoryTools.](https://u6.satisfactorytools.com/production?share=GB4B0mmEDpsGhR4rpbYm)

[Here is the closest I can get to that in FactorioLab.](https://factoriolab.github.io/list?z=eJwrMNayNNDSylJLClMr1tIyqHPSq3PyrnMKq3NKqnN2r3NOrnNxq3Nxr3PxqHOJqnNJrEurS68rqStVKzMHADOpFCg_&v=7)

The first noticeable downside in FLab is how selecting or deselecting alt-recipes to exclude Caterium, Quartz, and Oil from consideration is a pain compared to SFTools. There, you can keep all alt-recipes enabled and just set Caterium, Quartz, and Oil limits to zero items/s.

Second, compare the flow graphs in both programs. When SFTools runs out of Copper Ore to produce Iron and Copper Ingots with the alloy alt-recipes, it uses the remaining Iron Ore (up to its limit) to produce Iron Ingots with the normal recipe. FLab cannot do this.

One might naively try to subtract the Iron Ore usage computed in FLab from the total iron limit desired, use the result to limit a second calculation with copper recipes disabled, and add the two calculations together, but this will not yield an optimal result because the ideal ratio of copper usage in Iron vs. Copper Alloy Ingot production changes when Iron Ingots can also be produced purely from Iron Ore.

**Comment by dcbroad3** [comment]
@TacticalMook FactorioLab definitely supports your #2, but because it doesn't support #1 it is difficult to force it to find a solution that includes multiple alternate recipes.
If you solve for oil products in vanilla Factorio, lab will include multiple recipes for several items. It will only do so when it thinks that is a lower 'cost', however.
